# Generated by Django 3.1 on 2020-09-17 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rard.users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentableText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('apparatus_criticus', models.TextField(blank=True, default='')),
                ('commentary', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentary_for', to='research.commentabletext')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FragmentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('credit', models.CharField(blank=True, max_length=128)),
                ('copyright_status', models.CharField(blank=True, max_length=128)),
                ('name_and_attribution', models.CharField(blank=True, max_length=128)),
                ('public_release', models.BooleanField(default=False)),
                ('upload', models.ImageField(upload_to='uploads')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OriginalText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('apparatus_criticus', models.TextField(blank=True, default='')),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.fragment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('translator_name', models.CharField(max_length=128)),
                ('translated_text', models.TextField()),
                ('original_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.originaltext')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fragment',
            name='definite_works',
            field=models.ManyToManyField(blank=True, related_name='definite_fragments', to='research.Work'),
        ),
        migrations.AddField(
            model_name='fragment',
            name='images',
            field=models.ManyToManyField(blank=True, to='research.FragmentImage'),
        ),
        migrations.AddField(
            model_name='fragment',
            name='possible_works',
            field=models.ManyToManyField(blank=True, related_name='possible_fragments', to='research.Work'),
        ),
        migrations.AddField(
            model_name='fragment',
            name='topics',
            field=models.ManyToManyField(blank=True, to='research.Topic'),
        ),
        migrations.CreateModel(
            name='Concordance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=128)),
                ('identifier', models.CharField(max_length=128)),
                ('original_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.originaltext')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.commentabletext')),
                ('user', models.ForeignKey(on_delete=models.SET(rard.users.models.User.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BibliographyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('page', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.commentabletext')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Antiquarian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('re_code', models.CharField(blank=True, default='', max_length=64)),
                ('biography', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biography_for', to='research.commentabletext')),
                ('works', models.ManyToManyField(blank=True, to='research.Work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
