# Generated by Django 3.1 on 2020-09-28 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import rard.research.models.mixins
import rard.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antiquarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('re_code', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(rard.research.models.mixins.TextObjectFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CitingWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('author', models.CharField(blank=True, max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('edition', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('credit', models.CharField(blank=True, max_length=128)),
                ('copyright_status', models.CharField(blank=True, max_length=128)),
                ('name_and_attribution', models.CharField(blank=True, max_length=128)),
                ('public_release', models.BooleanField(default=False)),
                ('upload', models.ImageField(upload_to='uploads')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OriginalText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('content', models.TextField()),
                ('apparatus_criticus', models.TextField(blank=True, default='')),
                ('citing_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.citingwork')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextObjectField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('subtitle', models.CharField(blank=True, max_length=128)),
                ('number_of_volumes', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('translator_name', models.CharField(max_length=128)),
                ('translated_text', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('original_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.originaltext')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('apparatus_criticus', models.TextField(blank=True, default='')),
                ('commentary', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentary_for_testimonium', to='research.textobjectfield')),
                ('definite_antiquarians', models.ManyToManyField(blank=True, related_name='definite_testimoniums', to='research.Antiquarian')),
                ('definite_works', models.ManyToManyField(blank=True, related_name='definite_testimoniums', to='research.Work')),
                ('images', models.ManyToManyField(blank=True, to='research.Image')),
                ('possible_antiquarians', models.ManyToManyField(blank=True, related_name='possible_testimoniums', to='research.Antiquarian')),
                ('possible_works', models.ManyToManyField(blank=True, related_name='possible_testimoniums', to='research.Work')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(rard.research.models.mixins.TextObjectFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('apparatus_criticus', models.TextField(blank=True, default='')),
                ('commentary', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentary_for_fragment', to='research.textobjectfield')),
                ('definite_antiquarians', models.ManyToManyField(blank=True, related_name='definite_fragments', to='research.Antiquarian')),
                ('definite_works', models.ManyToManyField(blank=True, related_name='definite_fragments', to='research.Work')),
                ('images', models.ManyToManyField(blank=True, to='research.Image')),
                ('possible_antiquarians', models.ManyToManyField(blank=True, related_name='possible_fragments', to='research.Antiquarian')),
                ('possible_works', models.ManyToManyField(blank=True, related_name='possible_fragments', to='research.Work')),
                ('topics', models.ManyToManyField(blank=True, to='research.Topic')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(rard.research.models.mixins.TextObjectFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Concordance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('source', models.CharField(max_length=128)),
                ('identifier', models.CharField(max_length=128)),
                ('original_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.originaltext')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=models.SET(rard.users.models.User.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BibliographyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('page', models.CharField(max_length=128)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='antiquarian',
            name='biography',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biography_for', to='research.textobjectfield'),
        ),
        migrations.AddField(
            model_name='antiquarian',
            name='works',
            field=models.ManyToManyField(blank=True, to='research.Work'),
        ),
    ]
