# Generated by Django 3.1 on 2020-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='testimonium',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
