# Generated by Django 3.1 on 2020-10-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20201001_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concordance',
            options={'ordering': ('source', 'identifier')},
        ),
    ]
