# Generated by Django 3.1 on 2020-10-08 16:04

from django.db import migrations


PROJECT_GROUP_NAME = 'Project Team'
ADMIN_GROUP_NAME = 'Admin Team'


def add_model_permissions(group, model, ContentType, Permission):
    content_type = ContentType.objects.get_for_model(model)
    permissions = Permission.objects.filter(content_type=content_type)
    for permission in permissions:
        group.permissions.add(permission)


def create_default_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    
    RESEARCH_MODELS = [
        'Antiquarian',
        'BibliographyItem',
        'CitingWork',
        'Comment',
        'Concordance',
        'Fragment',
        'Image',
        'OriginalText',
        'Testimonium',
        'Topic',
        'Translation',
        'Work',
    ]

    project_group = Group.objects.create(name=PROJECT_GROUP_NAME)
    for model_name in RESEARCH_MODELS:
        model = apps.get_model("research", model_name)
        add_model_permissions(project_group, model, ContentType, Permission)

    # set up specific admin permissions here
    admin_group = Group.objects.create(name=ADMIN_GROUP_NAME)
    User = apps.get_model("users", "User")
    add_model_permissions(admin_group, User, ContentType, Permission)
    # add extra permissions here
    ADMIN_EXTRA_PERMS = [
        'view_logentry',
        'change_group',
        'view_group',
        'change_permission',
        'view_permission'
    ]
    for codename in ADMIN_EXTRA_PERMS:
        admin_group.permissions.add(Permission.objects.get(codename=codename))


def delete_default_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get(name=ADMIN_GROUP_NAME).delete()
    Group.objects.get(name=PROJECT_GROUP_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20201007_1335'),
    ]

    operations = [
        migrations.RunPython(create_default_groups, delete_default_groups)
    ]
