# Generated by Django 3.1 on 2020-10-20 14:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_create_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fragment',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='testimonium',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='definite_antiquarians',
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='definite_works',
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='possible_antiquarians',
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='possible_works',
        ),
        migrations.RemoveField(
            model_name='testimonium',
            name='definite_antiquarians',
        ),
        migrations.RemoveField(
            model_name='testimonium',
            name='definite_works',
        ),
        migrations.RemoveField(
            model_name='testimonium',
            name='possible_antiquarians',
        ),
        migrations.RemoveField(
            model_name='testimonium',
            name='possible_works',
        ),
        migrations.AlterField(
            model_name='fragment',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='testimonium',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='TestimoniumLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('definite', models.BooleanField(default=False)),
                ('antiquarian', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimoniumlinks', to='research.antiquarian')),
                ('testimonium', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_testimonium_links', to='research.testimonium')),
                ('work', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_work_testimonium_links', to='research.work')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FragmentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('definite', models.BooleanField(default=False)),
                ('antiquarian', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fragmentlinks', to='research.antiquarian')),
                ('fragment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_fragment_links', to='research.fragment')),
                ('work', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_work_fragment_links', to='research.work')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='antiquarian',
            name='fragments',
            field=models.ManyToManyField(blank=True, related_name='linked_antiquarians', through='research.FragmentLink', to='research.Fragment'),
        ),
        migrations.AddField(
            model_name='antiquarian',
            name='testimonia',
            field=models.ManyToManyField(blank=True, related_name='linked_antiquarians', through='research.TestimoniumLink', to='research.Testimonium'),
        ),
    ]
