# Generated by Django 3.1 on 2020-10-28 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_auto_20201022_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='number_of_volumes',
        ),
        migrations.AddField(
            model_name='work',
            name='number_of_books',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='antiquarian',
            name='re_code',
            field=models.CharField(max_length=64, unique=True, verbose_name='RE Number'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=128)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.work')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='fragmentlink',
            name='book',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_book_fragment_links', to='research.book'),
        ),
        migrations.AddField(
            model_name='testimoniumlink',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_book_testimonium_links', to='research.book'),
        ),
    ]
