# Generated by Django 3.1 on 2020-10-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20201028_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antiquarian',
            old_name='circa',
            new_name='circa1',
        ),
        migrations.AddField(
            model_name='antiquarian',
            name='circa2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antiquarian',
            name='dates_type',
            field=models.CharField(blank=True, choices=[('lived', 'Lived'), ('active', 'Active')], max_length=16),
        ),
        migrations.AddField(
            model_name='book',
            name='circa1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='circa2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='year1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='year2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='year_type',
            field=models.CharField(blank=True, choices=[('range', 'From/To'), ('before', 'Before'), ('after', 'After'), ('single', 'Single Year')], max_length=16),
        ),
        migrations.AddField(
            model_name='work',
            name='circa1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='circa2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='year1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='year2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='year_type',
            field=models.CharField(blank=True, choices=[('range', 'From/To'), ('before', 'Before'), ('after', 'After'), ('single', 'Single Year')], max_length=16),
        ),
    ]
