# Generated by Django 3.1 on 2020-11-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_objectlock_objectlockrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectlock',
            name='locked_until',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
