# Generated by Django 3.1 on 2020-11-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_symbol_symbolgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragment',
            name='apparatus_criticus',
        ),
        migrations.RemoveField(
            model_name='testimonium',
            name='apparatus_criticus',
        ),
    ]
