# Generated by Django 3.1 on 2020-11-19 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_auto_20201117_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antiquarian',
            old_name='biography',
            new_name='introduction',
        ),
    ]
