# Generated by Django 3.1 on 2020-11-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_auto_20201117_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliographyitem',
            options={'ordering': ['author_name']},
        ),
        migrations.RenameField(
            model_name='bibliographyitem',
            old_name='author',
            new_name='author_name',
        ),
        migrations.RemoveField(
            model_name='bibliographyitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='bibliographyitem',
            name='title',
        ),
        migrations.AddField(
            model_name='bibliographyitem',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
