# Generated by Django 3.1 on 2020-11-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_auto_20201117_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliographyitem',
            options={'ordering': ['authors']},
        ),
        migrations.RemoveField(
            model_name='bibliographyitem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bibliographyitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='bibliographyitem',
            name='title',
        ),
        migrations.AddField(
            model_name='bibliographyitem',
            name='authors',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='bibliographyitem',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
