# Generated by Django 3.1 on 2020-11-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_auto_20201117_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliographyitem',
            options={'ordering': ['author_surnames']},
        ),
        migrations.RemoveField(
            model_name='bibliographyitem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bibliographyitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='bibliographyitem',
            name='title',
        ),
        migrations.AddField(
            model_name='bibliographyitem',
            name='author_surnames',
            field=models.CharField(default='', help_text='Comma-separated list of surnames to be used for ordering', max_length=512),
        ),
        migrations.AddField(
            model_name='bibliographyitem',
            name='authors',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='bibliographyitem',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bibliographyitem',
            name='year',
            field=models.IntegerField(blank=True, default=None, help_text='Optional year to use for second-order sorting of entries', null=True),
        ),
    ]
