# Generated by Django 3.1 on 2020-11-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_auto_20201117_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['antiquarian__name', 'name']},
        ),
    ]
