# Generated by Django 3.1 on 2020-11-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_auto_20201124_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antiquarian',
            options={'ordering': ['order_name', 're_code']},
        ),
        migrations.AddField(
            model_name='antiquarian',
            name='order_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
