# Generated by Django 3.1 on 2020-12-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_auto_20201126_1426'),
        ('research', '0013_auto_20201125_1715'),
    ]

    operations = [
    ]
