# Generated by Django 3.1 on 2020-12-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_merge_20201202_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiquarian',
            name='introduction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduction_for', to='research.textobjectfield'),
        ),
    ]
