# Generated by Django 3.1 on 2020-12-09 10:24

from django.db import migrations, models
import django.db.models.deletion


def copy_work_links(apps, schema_editor):
    Antiquarian = apps.get_model("research", "Antiquarian")
    WorkLink = apps.get_model("research", "WorkLink")
    for a in Antiquarian.objects.all():
        for count, work in enumerate(a.works.all()):
            WorkLink.objects.create(antiquarian=a, work=work, order=count)


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0017_auto_20201209_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=None, null=True)),
                ('antiquarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.antiquarian')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.work')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RunPython(copy_work_links, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='antiquarian',
            name='works',
        ),
        migrations.AddField(
            model_name='antiquarian',
            name='works',
            field=models.ManyToManyField(blank=True, through='research.WorkLink', to='research.Work'),
        ),
    ]
