# Generated by Django 3.1 on 2020-12-10 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0019_topiclink'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragmentlink',
            name='work_order',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testimoniumlink',
            name='work_order',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fragmentlink',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_book_fragmentlinks', to='research.book'),
        ),
        migrations.AlterField(
            model_name='fragmentlink',
            name='fragment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_fragmentlinks', to='research.fragment'),
        ),
        migrations.AlterField(
            model_name='fragmentlink',
            name='work',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_work_fragmentlinks', to='research.work'),
        ),
        migrations.AlterField(
            model_name='testimoniumlink',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_book_testimoniumlinks', to='research.book'),
        ),
        migrations.AlterField(
            model_name='testimoniumlink',
            name='testimonium',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_testimoniumlinks', to='research.testimonium'),
        ),
        migrations.AlterField(
            model_name='testimoniumlink',
            name='work',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_work_testimoniumlinks', to='research.work'),
        ),
    ]
