# Generated by Django 3.1 on 2020-12-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0021_anonymousfragment_anonymousfragmentlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originaltext',
            options={'ordering': ('citing_work', 'reference')},
        ),
    ]
