# Generated by Django 3.1 on 2020-12-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0022_auto_20201215_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliographyitem',
            name='year',
            field=models.CharField(blank=True, default='', help_text='Optional date info to use for second-order sorting of entries', max_length=512),
        ),
    ]
