# Generated by Django 3.1 on 2020-12-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0023_auto_20201215_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bibliographyitem',
            old_name='content',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='bibliographyitem',
            name='authors',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='bibliographyitem',
            name='year',
            field=models.CharField(blank=True, default='', help_text='Optional date info to use for second-order sorting e.g. 1500a', max_length=512),
        ),
    ]
