# Generated by Django 3.1 on 2020-12-17 16:03

from django.db import migrations, models
import django.db.models.deletion


def copy_anonymous_topic_links(apps, schema_editor):
    Topic = apps.get_model("research", "Topic")
    AnonymousTopicLink = apps.get_model("research", "AnonymousTopicLink")
    for t in Topic.objects.all():
        for count, fragment in enumerate(t.anonymousfragment_set.all()):
            AnonymousTopicLink.objects.create(topic=t, fragment=fragment, order=count)


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0025_auto_20201217_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousTopicLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=None, null=True)),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.anonymousfragment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RunPython(copy_anonymous_topic_links, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='anonymousfragment',
            name='topics',
        ),
        migrations.AddField(
            model_name='anonymousfragment',
            name='topics',
            field=models.ManyToManyField(blank=True, through='research.AnonymousTopicLink', to='research.Topic'),
        ),
    ]
