# Generated by Django 3.1 on 2020-12-17 17:10

from django.db import migrations


def init_topic_order(apps, schema_editor):
    Topic = apps.get_model("research", "Topic")
    for count, t in enumerate(Topic.objects.filter(order__isnull=True)):
        t.order = count
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0027_auto_20201217_1633'),
    ]

    operations = [
        migrations.RunPython(init_topic_order, migrations.RunPython.noop),
    ]
