# Generated by Django 3.1 on 2021-01-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0028_ensure_topic_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiquarian',
            name='circa1',
            field=models.BooleanField(default=False, verbose_name='Circa'),
        ),
        migrations.AlterField(
            model_name='antiquarian',
            name='circa2',
            field=models.BooleanField(default=False, verbose_name='Circa'),
        ),
        migrations.AlterField(
            model_name='book',
            name='circa1',
            field=models.BooleanField(default=False, verbose_name='Circa'),
        ),
        migrations.AlterField(
            model_name='book',
            name='circa2',
            field=models.BooleanField(default=False, verbose_name='Circa'),
        ),
        migrations.AlterField(
            model_name='work',
            name='circa1',
            field=models.BooleanField(default=False, verbose_name='Circa'),
        ),
        migrations.AlterField(
            model_name='work',
            name='circa2',
            field=models.BooleanField(default=False, verbose_name='Circa'),
        ),
    ]
