# Generated by Django 3.1 on 2021-01-12 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0029_auto_20210105_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppositumFragmentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('definite', models.BooleanField(default=False)),
                ('work_order', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='anonymousfragment',
            name='fragments',
            field=models.ManyToManyField(blank=True, related_name='apposita', to='research.Fragment'),
        ),
        migrations.DeleteModel(
            name='AnonymousFragmentLink',
        ),
        migrations.AddField(
            model_name='appositumfragmentlink',
            name='anonymous_fragment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appositumfragmentlinks_from', to='research.anonymousfragment'),
        ),
        migrations.AddField(
            model_name='appositumfragmentlink',
            name='antiquarian',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appositumfragmentlinks', to='research.antiquarian'),
        ),
        migrations.AddField(
            model_name='appositumfragmentlink',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_book_appositumfragmentlinks', to='research.book'),
        ),
        migrations.AddField(
            model_name='appositumfragmentlink',
            name='link_object',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.fragmentlink'),
        ),
        migrations.AddField(
            model_name='appositumfragmentlink',
            name='linked_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appositumfragmentlinks_to', to='research.fragment'),
        ),
        migrations.AddField(
            model_name='appositumfragmentlink',
            name='work',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiquarian_work_appositumfragmentlinks', to='research.work'),
        ),
    ]
