# Generated by Django 3.1 on 2021-01-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0030_auto_20210112_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='appositumfragmentlink',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
