# Generated by Django 3.1 on 2021-01-22 16:58

from django.db import migrations, models



def copy_text_object_fields(apps, schema_editor):
    Antiquarian = apps.get_model("research", "Antiquarian")
    AnonymousFragment = apps.get_model("research", "AnonymousFragment")
    Fragment = apps.get_model("research", "Fragment")
    Testimonium = apps.get_model("research", "Testimonium")

    model_fields = {
        Antiquarian: 'introduction',
        AnonymousFragment: 'commentary',
        Fragment: 'commentary',
        Testimonium: 'commentary',

    }
    
    for class_, field_name in model_fields.items():
        print('class is %s' % class_)
        for obj in class_.objects.all():
            print('object %s' % obj)
            content = getattr(obj, field_name).content
            print('content %s' % content)
            new_field_name = 'new_%s' % field_name
            setattr(obj, new_field_name, content)
            print('have set %s to %s' % (new_field_name, getattr(obj, new_field_name)))
            obj.save()
            print('saved')


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0031_appositumfragmentlink_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousfragment',
            name='new_commentary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='antiquarian',
            name='new_introduction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fragment',
            name='new_commentary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testimonium',
            name='new_commentary',
            field=models.TextField(default=''),
        ),
        migrations.RunPython(copy_text_object_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='anonymousfragment',
            name='commentary',
        ),
        migrations.RemoveField(
            model_name='antiquarian',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='commentary',
        ),
        migrations.RemoveField(
            model_name='testimonium',
            name='commentary',
        ),
        migrations.RenameField(
            model_name='anonymousfragment',
            old_name='new_commentary',
            new_name='commentary',
        ),
        migrations.RenameField(
            model_name='antiquarian',
            old_name='new_introduction',
            new_name='introduction',
        ),
        migrations.RenameField(
            model_name='fragment',
            old_name='new_commentary',
            new_name='commentary',
        ),
        migrations.RenameField(
            model_name='testimonium',
            old_name='new_commentary',
            new_name='commentary',
        ),
    ]
