# Generated by Django 3.1 on 2021-01-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0032_history_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalantiquarian',
            name='introduction',
        ),
    ]
