# Generated by Django 3.1 on 2021-02-10 17:42

from django.db import migrations
import rard.utils.basemodel


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0032_history_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloriginaltext',
            name='apparatus_criticus',
            field=rard.utils.basemodel.DynamicTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicaltextobjectfield',
            name='content',
            field=rard.utils.basemodel.DynamicTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='originaltext',
            name='apparatus_criticus',
            field=rard.utils.basemodel.DynamicTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='textobjectfield',
            name='content',
            field=rard.utils.basemodel.DynamicTextField(blank=True, default=''),
        ),
    ]
