# Generated by Django 3.1 on 2021-02-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0033_auto_20210210_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloriginaltext',
            name='reference',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='originaltext',
            name='reference',
            field=models.CharField(max_length=128),
        ),
    ]
