# Generated by Django 3.1 on 2021-01-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0034_historicalrecordlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousfragment',
            name='commentary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='antiquarian',
            name='introduction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='commentary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalanonymousfragment',
            name='commentary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalantiquarian',
            name='introduction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalfragment',
            name='commentary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicaltestimonium',
            name='commentary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testimonium',
            name='commentary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
