# Generated by Django 3.1 on 2021-02-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0036_auto_20210224_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousfragment',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
        migrations.AlterField(
            model_name='antiquarian',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
        migrations.AlterField(
            model_name='historicalanonymousfragment',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
        migrations.AlterField(
            model_name='historicalantiquarian',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfragment',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
    ]
