# Generated by Django 3.1 on 2021-03-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0040_historicalcitingauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='citingauthor',
            name='date_range',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='citingauthor',
            name='order_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='citingauthor',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
        migrations.AddField(
            model_name='citingwork',
            name='date_range',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='citingwork',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
        migrations.AddField(
            model_name='historicalcitingauthor',
            name='date_range',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='historicalcitingauthor',
            name='order_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='historicalcitingauthor',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
        migrations.AddField(
            model_name='historicalcitingwork',
            name='date_range',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='historicalcitingwork',
            name='order_year',
            field=models.IntegerField(blank=True, default=None, help_text='Enter a negative integer value for BC, positive for AD', null=True),
        ),
    ]
