# Generated by Django 3.1 on 2021-03-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0040_auto_20210329_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloriginaltext',
            name='apparatus_criticus',
        ),
        migrations.RemoveField(
            model_name='originaltext',
            name='apparatus_criticus',
        ),
    ]
