# Generated by Django 3.1 on 2021-03-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0041_auto_20210316_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citingauthor',
            options={'ordering': ['order_name']},
        ),
    ]
