# Generated by Django 3.1 on 2021-03-22 09:52

from django.db import migrations, models
import rard.research.models.citing_work


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0042_auto_20210316_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citingwork',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(rard.research.models.citing_work.CitingAuthor.get_anonymous_citing_author), to='research.citingauthor'),
        ),
    ]
