# Generated by Django 3.1 on 2021-03-23 16:42

import re
from django.db import migrations, models


def init_reference_order(apps, schema_editor):
    OriginalText = apps.get_model("research", "OriginalText")
    HistoricalOriginalText = apps.get_model(
        "research", "HistoricalOriginalText"
    )

    def set_reference_order_data(_class):
        # use the first occurance of a number in the reference for
        # the reference order where not set
        for item in _class.objects.all():
            try:
                match = re.search(r'(\d+)', item.reference)
                if match is not None:
                    item.reference_order = match.group(1)
                    item.save()
            except TypeError:
                # not set
                pass

    for _class in [OriginalText, HistoricalOriginalText]:
        set_reference_order_data(_class)


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0044_auto_20210323_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloriginaltext',
            name='reference_order',
            field=models.IntegerField(blank=False, default=None, null=True),
        ),
        migrations.AddField(
            model_name='originaltext',
            name='reference_order',
            field=models.IntegerField(blank=False, default=None, null=True),
        ),
        migrations.RunPython(init_reference_order, migrations.RunPython.noop),
    ]
