# Generated by Django 3.1 on 2021-03-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0045_auto_20210323_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citingauthor',
            name='order_name',
            field=models.CharField(blank=True, default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcitingauthor',
            name='order_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
