# Generated by Django 3.1 on 2021-03-29 11:23

from django.db import migrations
import rard.utils.basemodel


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0046_apparatuscriticusitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloriginaltext',
            name='content',
            field=rard.utils.basemodel.DynamicTextField(),
        ),
        migrations.AlterField(
            model_name='originaltext',
            name='content',
            field=rard.utils.basemodel.DynamicTextField(),
        ),
    ]
