# Generated by Django 3.1 on 2021-04-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0047_auto_20210329_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originaltext',
            options={'ordering': ('citing_work', 'reference_order')},
        ),
        migrations.AddField(
            model_name='historicaloriginaltext',
            name='reference_order_new',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='originaltext',
            name='reference_order_new',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
