# Generated by Django 3.1 on 2021-04-21 07:25

from django.db import migrations


def pad_reference_order(apps, schema_editor):
    """Convert a plain number ordering to string 00123 style."""
    # We can't import the OriginalText model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    OriginalText = apps.get_model('research', 'OriginalText')
    HistoricalOriginalText = apps.get_model(
        'research', 'HistoricalOriginalText'
    )
    for _class in [OriginalText, HistoricalOriginalText]:
        for text in _class.objects.all():
            if text.reference_order:
                text.reference_order_new = str(text.reference_order).zfill(5)
                text.save()


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0048_auto_20210421_0721'),
    ]

    operations = [
        # We don't supply a reverse migration as it would lose data
        migrations.RunPython(pad_reference_order),
    ]
