# Generated by Django 3.1 on 2021-04-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0049_pad_reference_order_20210421_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originaltext',
            options={'ordering': ('citing_work', 'reference_order_new')},
        ),
        migrations.RemoveField(
            model_name='historicaloriginaltext',
            name='reference_order',
        ),
        migrations.RemoveField(
            model_name='originaltext',
            name='reference_order',
        ),
    ]
