# Generated by Django 3.1 on 2021-08-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0052_auto_20210728_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concordance',
            name='original_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concordances', to='research.originaltext'),
        ),
    ]
