# Generated by Django 3.2 on 2021-10-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0053_auto_20210812_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloriginaltext',
            name='apparatus_criticus_blank',
            field=models.BooleanField(default=False, verbose_name='apparatus criticus intentionally blank'),
        ),
        migrations.AddField(
            model_name='originaltext',
            name='apparatus_criticus_blank',
            field=models.BooleanField(default=False, verbose_name='apparatus criticus intentionally blank'),
        ),
    ]
