# Generated by Django 3.2 on 2021-12-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0054_auto_20211028_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloriginaltext',
            name='apparatus_criticus_blank',
            field=models.BooleanField(default=False, verbose_name='no apparatus criticus exists'),
        ),
        migrations.AlterField(
            model_name='originaltext',
            name='apparatus_criticus_blank',
            field=models.BooleanField(default=False, verbose_name='no apparatus criticus exists'),
        ),
    ]
