# Generated by Django 3.2 on 2022-07-07 13:23

from django.db import migrations


def reindex_all_fragment_links(apps, schema_editor):
    Antiquarian = apps.get_model("research", "Antiquarian")
    for antiquarian in Antiquarian.objects.all():
        antiquarian.reindex_fragment_and_testimonium_links()


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0056_faceted_search"),
    ]

    operations = [
        migrations.RunPython(reindex_all_fragment_links, reindex_all_fragment_links)
    ]
