# Generated by Django 3.2 on 2021-12-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0056_auto_20211214_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousfragment',
            name='plain_commentary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fragment',
            name='plain_commentary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalanonymousfragment',
            name='plain_commentary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalfragment',
            name='plain_commentary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicaltestimonium',
            name='plain_commentary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testimonium',
            name='plain_commentary',
            field=models.TextField(default=''),
        ),
    ]
