# Generated by Django 3.2 on 2022-07-07 13:23
import itertools

from django.db import migrations


def reindex_all_fragment_links(apps, schema_editor):
    Antiquarian = apps.get_model("research", "Antiquarian")
    for ant in Antiquarian.objects.all():
        to_reorder = itertools.chain(
                        ant.testimoniumlinks.all().filter(work__isnull=True).distinct(),
                        ant.testimoniumlinks.all()
                        .filter(work__isnull=False)
                        .order_by("work__worklink__order", "work_order")
                        .distinct(),
                    )


        for count, link in enumerate(to_reorder):
            if link.order != count:
                link.order = count
                link.save()


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0056_faceted_search"),
    ]

    operations = [
        migrations.RunPython(reindex_all_fragment_links, reindex_all_fragment_links)
    ]
