# Generated by Django 3.2 on 2021-12-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0057_auto_20211215_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiquarian',
            name='plain_introduction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalantiquarian',
            name='plain_introduction',
            field=models.TextField(default=''),
        ),
    ]
