# Generated by Django 3.2 on 2022-07-14 09:39

from django.db import migrations


def give_anonymoustopiclinks_order(apps, schema_editor):
    Topic = apps.get_model("research", "Topic")
    AnonymousTopicLink = apps.get_model("research", "AnonymousTopicLink")

    for topic in Topic.objects.all():
        qs = AnonymousTopicLink.objects.filter(topic=topic).order_by("fragment__order")
        for count, link in enumerate(qs):
            link.order = count
            link.save()


def reverse_give_anonymoustopiclinks_order(apps, schema_editor):
    Topic = apps.get_model("research", "Topic")
    AnonymousTopicLink = apps.get_model("research", "AnonymousTopicLink")

    for topic in Topic.objects.all():
        qs = AnonymousTopicLink.objects.filter(topic=topic).order_by("fragment__order")
        for count, link in enumerate(qs):
            link.order = None
            link.save()


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0057_reindex_testimonia_links"),
    ]

    operations = [
        migrations.RunPython(
            give_anonymoustopiclinks_order, reverse_give_anonymoustopiclinks_order
        )
    ]
