# Generated by Django 3.2 on 2022-01-26 12:39

from django.db import migrations

from rard.utils.text_processors import make_plain_text

def save_objects_with_plain_text_fields(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Antiquarian = apps.get_model("research", "Antiquarian")
    for object in Antiquarian.objects.using(db_alias).all():
        if object.introduction:
            object.plain_introduction = make_plain_text(object.introduction.content)
            object.save()
    Fragment = apps.get_model("research", "Fragment")
    for object in Fragment.objects.using(db_alias).all():
        if object.commentary:
            object.plain_commentary = make_plain_text(object.commentary.content)
            object.save()
    AnonymousFragment = apps.get_model("research", "AnonymousFragment")
    for object in AnonymousFragment.objects.using(db_alias).all():
        if object.commentary:
            object.plain_commentary = make_plain_text(object.commentary.content)
            object.save()
    Testimonium = apps.get_model("research", "Testimonium")
    for object in Testimonium.objects.using(db_alias).all():
        if object.commentary:
            object.plain_commentary = make_plain_text(object.commentary.content)
            object.save()
    OriginalText = apps.get_model("research", "OriginalText")
    for object in OriginalText.objects.using(db_alias).all():
        if object.content:
            object.plain_content = make_plain_text(object.content)
            object.save()
    Translation = apps.get_model("research", "Translation")
    for object in Translation.objects.using(db_alias).all():
        if object.translated_text:
            object.plain_translated_text = make_plain_text(object.translated_text)
            object.save()



class Migration(migrations.Migration):

    dependencies = [
        ('research', '0058_auto_20211215_1408'),
    ]

    operations = [
        migrations.RunPython(save_objects_with_plain_text_fields)
    ]
