# Generated by Django 3.2 on 2022-07-26 14:39

from django.db import migrations, models
import django.db.models.deletion


def move_ref_info_to_object(apps, schema_editor):
    OriginalText = apps.get_model("research", "OriginalText")
    Reference = apps.get_model("research", "Reference")
    for i in OriginalText.objects.all():
        Reference.objects.create(
            text=i.reference, order=i.reference_order, original_text=i
        ).save()


def reverse_move_ref_info_to_object(apps, schema_editor):
    Reference = apps.get_model("research", "Reference")
    for i in Reference.objects.all():
        i.original_text.reference = i.text
        i.original_text.reference_order = i.order
        i.original_text.save()

    Reference.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0058_anonymous_topiclink_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=128)),
                ("order", models.CharField(default=None, max_length=100, null=True)),
                (
                    "original_text",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="research.originaltext",
                    ),
                ),
            ],
        ),
        migrations.RunPython(move_ref_info_to_object, reverse_move_ref_info_to_object),
        migrations.AlterModelOptions(
            name="originaltext",
            options={},
        ),
        migrations.RemoveField(
            model_name="historicaloriginaltext",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="historicaloriginaltext",
            name="reference_order",
        ),
        migrations.RemoveField(
            model_name="originaltext",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="originaltext",
            name="reference_order",
        ),
    ]
