# Generated by Django 3.2 on 2022-08-10 09:05

from django.db import migrations, models
import django.db.models.deletion


def move_ref_info_to_object(apps, schema_editor):
    OriginalText = apps.get_model("research", "OriginalText")
    Reference = apps.get_model("research", "Reference")
    for i in OriginalText.objects.all():
        Reference.objects.create(reference_position=i.reference, original_text=i).save()


def reverse_move_ref_info_to_object(apps, schema_editor):
    Reference = apps.get_model("research", "Reference")
    for i in Reference.objects.all():
        i.original_text.reference = i.reference_position
        i.original_text.save()

    Reference.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0059_add_temp_default_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("editor", models.CharField(blank=True, max_length=128)),
                ("reference_position", models.CharField(max_length=50)),
                (
                    "original_text",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="research.originaltext",
                    ),
                ),
            ],
        ),
        migrations.RunPython(move_ref_info_to_object, reverse_move_ref_info_to_object),
        migrations.RemoveField(
            model_name="historicaloriginaltext",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="originaltext",
            name="reference",
        ),
    ]
