# Generated by Django 3.2 on 2022-09-19 08:37

from django.db import migrations, models

def move_bibliography_item_to_objects(apps,schema_editor):
    Antiquarian = apps.get_model("research","Antiquarian")
    for i in Antiquarian.objects.all():
        for b in i.bibliography_items_temp.all():
            i.bibligraphy_items.add(b)
        i.save()


def reverse_move_bibliography_item_to_objects(apps,schema_editor):
    Antiquarian = apps.get_model("research","Antiquarian")
    for i in Antiquarian.objects.all():
        for b in i.bibliography_items.all():
            i.bibliography_items_temp.add(b)
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('research', '0060_add_reference_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antiquarian',
            old_name='bibliography_items',
            new_name='bibliography_items_temp',
        ),
        migrations.AddField(
            model_name='antiquarian',
            name='bibliography_items',
            field=models.ManyToManyField(blank=True, related_query_name='biblography_items', to='research.BibliographyItem'),
        ),
        migrations.RunPython(move_bibliography_item_to_objects, reverse_move_bibliography_item_to_objects),
        migrations.RemoveField(
            model_name='antiquarian',
            name='bibliography_items_temp',
            
        ),

    ]
