# Generated by Django 3.2 on 2022-10-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0061_antiquarian_bibliography_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antiquarian',
            old_name='bibliography_items2',
            new_name='bibliography_items',
        ),
        migrations.RemoveField(
            model_name='bibliographyitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='bibliographyitem',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='historicalbibliographyitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='historicalbibliographyitem',
            name='object_id',
        ),
        
    ]
