# Generated by Django 3.2 on 2023-06-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0062_definite_possible_clarity"),
    ]

    def set_default_introduction(apps, schema_editor):
        Work = apps.get_model("research", "Work")
        Book = apps.get_model("research", "Book")

        # Set default introduction for existing works
        for work in Work.objects.all():
            work.introduction = f"Introduction for {work}"
            work.save()

        # Set default introduction for existing books
        for book in Book.objects.all():
            book.introduction = f"Introduction for {book}"
            book.save()

    operations = [
        migrations.AddField(
            model_name="book",
            name="introduction",
            field=models.OneToOneField(
                null=True,
                default="Introduction",
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="introduction_for_book",
                to="research.textobjectfield",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="introduction",
            field=models.OneToOneField(
                null=True,
                default="Introduction",
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="introduction_for_work",
                to="research.textobjectfield",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="plain_introduction",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalbook",
            name="plain_introduction",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalwork",
            name="plain_introduction",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="work",
            name="plain_introduction",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalbook",
            name="introduction",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="introduction_for_historical_book",
                to="research.textobjectfield",
            ),
        ),
        migrations.AddField(
            model_name="historicalwork",
            name="introduction",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="introduction_for_historical_work",
                to="research.textobjectfield",
            ),
        ),
    ]
