# Generated by Django 3.2 on 2023-06-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0062_definite_possible_clarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="introduction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="introduction_for_book",
                to="research.textobjectfield",
            ),
        ),
        migrations.AddField(
            model_name="historicalbook",
            name="introduction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="research.textobjectfield",
            ),
        ),
        migrations.AddField(
            model_name="historicalwork",
            name="introduction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="research.textobjectfield",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="introduction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="introduction_for_work",
                to="research.textobjectfield",
            ),
        ),
    ]
