# Generated by Django 3.2 on 2023-06-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0062_definite_possible_clarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="introduction",
            field=models.OneToOneField(
                "TextObjectField",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="introduction_for_book",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="introduction",
            field=models.OneToOneField(
                "TextObjectField",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="introduction_for_work",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="plain_introduction",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalbook",
            name="plain_introduction",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalwork",
            name="plain_introduction",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="work",
            name="plain_introduction",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalbook",
            name="introduction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="introduction_for_historical_book",
                to="research.textobjectfield",
            ),
        ),
        migrations.AddField(
            model_name="historicalwork",
            name="introduction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="introduction_for_historical_work",
                to="research.textobjectfield",
            ),
        ),
        # migrations.RunPython(set_default_introduction),
    ]
