# Generated by Django 3.2 on 2022-11-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0062_antiquarian_bibliography_items_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='citingauthor',
            name='bibliography_items',
            field=models.ManyToManyField(blank=True, related_query_name='bibliography_items', to='research.BibliographyItem'),
        ),
        migrations.AlterField(
            model_name='antiquarian',
            name='bibliography_items',
            field=models.ManyToManyField(blank=True, related_query_name='bibliography_items', to='research.BibliographyItem'),
        ),
    ]
