# Generated by Django 3.2 on 2024-01-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0066_remove_bibliography_item_gfk"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousfragment",
            name="mentioned_in",
            field=models.ManyToManyField(blank=True, to="research.TextObjectField"),
        ),
        migrations.AddField(
            model_name="fragment",
            name="mentioned_in",
            field=models.ManyToManyField(blank=True, to="research.TextObjectField"),
        ),
        migrations.AddField(
            model_name="testimonium",
            name="mentioned_in",
            field=models.ManyToManyField(blank=True, to="research.TextObjectField"),
        ),
    ]
