# Generated by Django 3.2 on 2024-03-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0068_public_commentary_mentions"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousfragment",
            name="duplicate_frags",
            field=models.ManyToManyField(
                blank=True,
                related_name="anonymousfragment_duplicate_fragments",
                to="research.Fragment",
            ),
        ),
        migrations.AddField(
            model_name="fragment",
            name="duplicate_frags",
            field=models.ManyToManyField(
                blank=True,
                related_name="fragment_duplicate_fragments",
                to="research.Fragment",
            ),
        ),
    ]
