# Generated by Django 3.2 on 2024-03-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0068_public_commentary_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousfragment',
            name='anonymous_fragments',
            field=models.ManyToManyField(blank=True, related_name='anonymous_apposita', to='research.AnonymousFragment'),
        ),
    ]
