# Generated by Django 3.2 on 2024-03-08 12:27

import re
import string
import unicodedata
from django.db import migrations
from django.utils.html import strip_tags


def strip_combining_and_make_plain(content):
    plain_text = make_plain_text(content)
    normalized = unicodedata.normalize("NFD", plain_text)
    return "".join([char for char in normalized if not unicodedata.combining(char)])


def make_plain_text(content):
    no_ufeff = content.replace("\ufeff", "")  # found around mentions for some reason
    no_tags = strip_tags(no_ufeff.replace("><", "> <"))
    no_html_chars = re.sub(r"&\w+;", " ", no_tags)
    no_punctuation = no_html_chars.translate(str.maketrans("", "", string.punctuation))
    no_lone_numbers = re.sub(r"\s\d{1,2}\s", " ", no_punctuation)  # mentions
    no_excess_space = re.sub(r" +", " ", no_lone_numbers)
    return no_excess_space


PLAIN_TEXT_MODEL_FIELDS = {
    "Antiquarian": "introduction",
    "Work": "introduction",
    "Fragment": "commentary",
    "AnonymousFragment": "commentary",
    "Testimonium": "commentary",
    "OriginalText": "content",
    "Translation": "translated_text",
}


def update_plain_text(apps, model_name, field_name, plaining_function):
    model = apps.get_model("research", model_name)
    for instance in model.objects.all():
        content = getattr(instance, field_name)
        setattr(instance, "plain_" + field_name, plaining_function(content))
        instance.save()


def update_plain_texts(apps, schema_editor):
    for model_name, field_name in PLAIN_TEXT_MODEL_FIELDS.items():
        update_plain_text(apps, model_name, field_name, strip_combining_and_make_plain)


def revert_plain_texts(apps, schema_editor):
    for model_name, field_name in PLAIN_TEXT_MODEL_FIELDS.items():
        update_plain_text(apps, model_name, field_name, make_plain_text)


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0069_anonymousfragment_anonymous_fragments"),
    ]

    operations = [migrations.RunPython(update_plain_texts, revert_plain_texts)]
