# Generated by Django 3.2 on 2024-09-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0073_new_concordance_model_etc"),
    ]

    operations = [
        migrations.AddField(
            model_name="citingauthor",
            name="introduction",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="introduction_for_citingauthor",
                to="research.textobjectfield",
            ),
        ),
        migrations.AddField(
            model_name="citingauthor",
            name="plain_introduction",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="citingwork",
            name="introduction",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="introduction_for_citingwork",
                to="research.textobjectfield",
            ),
        ),
        migrations.AddField(
            model_name="citingwork",
            name="plain_introduction",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalcitingauthor",
            name="introduction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="research.textobjectfield",
            ),
        ),
        migrations.AddField(
            model_name="historicalcitingauthor",
            name="plain_introduction",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalcitingwork",
            name="introduction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="research.textobjectfield",
            ),
        ),
        migrations.AddField(
            model_name="historicalcitingwork",
            name="plain_introduction",
            field=models.TextField(default=""),
        ),
    ]
