# Generated by Django 3.2 on 2025-04-28 10:45

from django.db import migrations, models


def create_testimonium_tags(apps, schema_editor):
    TestimoniumTag = apps.get_model('research', 'TestimoniumTag')
    tags = [
        "Modus Operandi",
        "Biography: Family",
        "Biography: General",
    ]
    for tag in tags:
        TestimoniumTag.objects.create(name=tag)

class Migration(migrations.Migration):

    dependencies = [
        ('research', '0074_adding_intros_to_citing_authors_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimoniumTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Testimonium Tag',
                'verbose_name_plural': 'Testimonium Tags',
            },
        ),
        migrations.AddField(
            model_name='testimonium',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='testimonia', to='research.TestimoniumTag', verbose_name='Tags'),
        ),
        migrations.RunPython(
            create_testimonium_tags,
            reverse_code=migrations.RunPython.noop,
        )
    ]
