# Generated by Django 3.2.25 on 2026-06-25 11:52

from django.db import migrations, models


def add_bibliographic_works(apps, schema_editor):
    """Run save on all Antiquarian objects to create 
    a new bibliographic work for each."""
    Antiquarian = apps.get_model("research", "Antiquarian")
    Work = apps.get_model("research", "Work")

    # Create an explicit bibliographic Work for each Antiquarian.
    for antiquarian in Antiquarian.objects.all():
        # If this antiquarian already has a bibliographic work, skip
        if (
            Work.objects.filter(bibliographic=True, antiquarian__pk=antiquarian.pk)
            .exists()
        ):
            continue

        w = Work.objects.create(name="Bibliographic Work", bibliographic=True)
        # attach via the m2m on the Antiquarian instance
        antiquarian.works.add(w)
        w.save()


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0075_add_testimonium_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwork',
            name='bibliographic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='bibliographic',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(add_bibliographic_works, reverse_code=migrations.RunPython.noop),
    ]
