# Generated by Django 3.2.25 on 2026-07-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0077_alter_worklink_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousfragment',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antiquarian',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citingauthor',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citingwork',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fragment',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalanonymousfragment',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalantiquarian',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcitingauthor',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcitingwork',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfragment',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltestimonium',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalwork',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonium',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
    ]
