# Generated by Django 3.2.25 on 2026-06-25 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0077_add_bibliographic_works'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worklink',
            options={'ordering': ['work__unknown', 'work__bibliographic', 'order']},
        ),
    ]
