# Generated by Django 3.2.25 on 2026-07-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0078_auto_20260721_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymousfragment',
            options={'ordering': ['order'], 'permissions': [('publish_anonymous_fragment', 'Can publish an anonymous fragment')]},
        ),
        migrations.AlterModelOptions(
            name='antiquarian',
            options={'ordering': ['order_name', 're_code'], 'permissions': [('publish_antiquarian', 'Can publish an antiquarian')]},
        ),
        migrations.AlterModelOptions(
            name='citingauthor',
            options={'ordering': ('order_name',), 'permissions': [('publish_citing_author', 'Can publish a citing author')]},
        ),
        migrations.AlterModelOptions(
            name='citingwork',
            options={'permissions': [('publish_citing_work', 'Can publish a citing work')]},
        ),
        migrations.AlterModelOptions(
            name='fragment',
            options={'ordering': ['pk'], 'permissions': [('publish_fragment', 'Can publish a fragment')]},
        ),
        migrations.AlterModelOptions(
            name='testimonium',
            options={'ordering': ['pk'], 'permissions': [('publish_testimonium', 'Can publish a testimonium')]},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['name'], 'permissions': [('publish_work', 'Can publish a work')]},
        ),
    ]
