# Generated by Django 3.2 on 2026-05-08 12:07

from django.db import migrations, models
from rard.utils.text_processors import fold_latin_and_remove_punctuation

def noop(_apps, _schema_editor):
    return


def add_folded_text_fields(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    OriginalText = apps.get_model("research", "OriginalText")
    for object in OriginalText.objects.using(db_alias).all():
        if object.plain_content:
            object.folded_content = fold_latin_and_remove_punctuation(object.plain_content)
            object.save()
    HistoricalOriginalText = apps.get_model(
        'research', 'HistoricalOriginalText'
    )
    for object in HistoricalOriginalText.objects.using(db_alias).all():
        if object.plain_content:
            object.folded_content = fold_latin_and_remove_punctuation(object.plain_content)
            object.save()


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0079_auto_20260721_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloriginaltext',
            name='folded_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='originaltext',
            name='folded_content',
            field=models.TextField(default=''),
        ),
        migrations.RunPython(
            code=add_folded_text_fields,
            reverse_code=noop,
        ),
    ]
