# Generated by Django 3.2.25 on 2026-07-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0079_auto_20260721_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymousfragment',
            options={'ordering': ['order'], 'permissions': [('set_publishable', 'Can set publishable status')]},
        ),
        migrations.AlterModelOptions(
            name='antiquarian',
            options={'ordering': ['order_name', 're_code'], 'permissions': [('set_publishable', 'Can set publishable status')]},
        ),
        migrations.AlterModelOptions(
            name='citingauthor',
            options={'ordering': ('order_name',), 'permissions': [('set_publishable', 'Can set publishable status')]},
        ),
        migrations.AlterModelOptions(
            name='citingwork',
            options={'permissions': [('set_publishable', 'Can set publishable status')]},
        ),
        migrations.AlterModelOptions(
            name='fragment',
            options={'ordering': ['pk'], 'permissions': [('set_publishable', 'Can set publishable status')]},
        ),
        migrations.AlterModelOptions(
            name='testimonium',
            options={'ordering': ['pk'], 'permissions': [('set_publishable', 'Can set publishable status')]},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['name'], 'permissions': [('set_publishable', 'Can set publishable status')]},
        ),
    ]
