# Run this script from the src/collation directory
import datetime
import tempfile
import os

# list of folds; each list of folds begins with the
# string to be folded to.
# We are assuming that each single character is sorted according to the
# order in which they appear in this list, which might not always be great.
order = [
#['ast', 'a est'], -- seems spaces mysteriously don't work.
#['ost', 'o est'],
#['umst', 'um est'],
['am', 'an'],
['ausa', 'aussa'],
['nn', 'bn'],
['tt', 'bt'],
['pp', 'bp'],
['rr', 'br'],
['ch', 'cch'],
['clu', 'culu'],
['Claud', 'Clod'],
['has', 'hasce'],
['his', 'hisce'],
['hos', 'hosce'],
['i', 'I', 'ii', 'j', 'J'],
['um', 'im'],
['lagr', 'lagl'],
['mb', 'nb'],
['ll', 'nl'],
['mm', 'nm'],
['mp', 'np', 'ndup'],
['rr', 'nr'],
['um', 'om'],
['u', 'U', 'v', 'V', 'y', 'Y'],
['uu', 'w', 'W'],
['ulc', 'ulch'],
['uul', 'uol', 'vul', 'vol'],
['ui', 'uui', 'uvi'],
['uum', 'uom'],
['x', 'X', 'xs'],
]

lc_identification = '''# Generated by latin.py
#
LC_IDENTIFICATION
title      "Latin folding for Frrant"
source     ""
address    ""
contact    ""
email      ""
tel        ""
fax        ""
language   "Latin"
territory  "Rome"
revision   "1.0"
date       "{0}"
END LC_IDENTIFICATION
#'''.format(datetime.datetime.utcnow().strftime('%Y-%m-%d'))

default_section = '''{0}
copy "{1}"
END {0}
#'''

def initial(fd):
    print(lc_identification, file=fd)

    for section in [
        'LC_PAPER',
        'LC_NAME',
        'LC_ADDRESS',
        'LC_TELEPHONE',
        'LC_MEASUREMENT']:
        print(default_section.format(section, 'i18n'), file=fd)

    for section in [
        'LC_CTYPE',
        'LC_NUMERIC',
        'LC_TIME',
        'LC_MONETARY',
        'LC_MESSAGES']:
        print(default_section.format(section, 'POSIX'), file=fd)

def make_id(cluster):
    return cluster.replace(' ', '-')

def letter_variant_list(form, cluster):
    st = '"'
    st1 = ''
    for letter in cluster:
        st1 = form.format(ord(letter))
        st += st1
    return len(cluster) == 1 and st1 or st + '"'

def letter_list(cluster):
    return letter_variant_list('<U{0:04X}>', cluster)

def level_1_list(cluster):
    return letter_variant_list('<S{0:04X}>', cluster.lower())

def level_2_list(cluster):
    return letter_variant_list('<BASE>', cluster)

def level_3_list(cluster):
    return letter_variant_list('<COMPAT>', cluster)

def level_4_list(cluster):
    if len(cluster) == 1:
        return '<U{0:04X}>'.format(ord(cluster))
    return 'IGNORE'

def levels(cluster):
    return '{0};{1};{2};{3}'.format(
        level_1_list(cluster),
        level_2_list(cluster),
        level_3_list(cluster),
        level_4_list(cluster)
    )

def lc_collate(fd):
    print('LC_COLLATE', file=fd)
    print('copy "iso14651_t1"', file=fd)

    for fld in order:
        for cluster in [v for v in fld[1:] if 1 < len(v)]:
            print('collating-element <{0}> from {1}'.format(
                make_id(cluster), letter_list(cluster)
            ), file=fd)

    print('reorder-after <AFTER-LATIN>', file=fd)

    for fld in order:
        if len(fld[0]) == 1:
            print('{0} {1}'.format(letter_list(fld[0]), levels(fld[0])), file=fd)
        for cluster in fld[1:]:
            llc = letter_list(cluster)
            if len(cluster) == 1:
                print('{0} {1}'.format(llc, levels(fld[0])), file=fd)
            else:
                print('<{0}> {1}'.format(make_id(cluster), levels(fld[0])), file=fd)

    print('reorder-end', file=fd)
    print('END LC_COLLATE', file=fd)
    print('#', file=fd)

with open('latin', 'w') as locale_def_file:
    initial(locale_def_file)
    lc_collate(locale_def_file)

# How to use in Postgres:
#
# create table names (id int, name text);
# insert into names (name) values ('ursula'),('bethany'),('victoria');
# select * from names order by name collate "latin";
# select * from names where name ilike '%u%' collate latin;

# Sadly, it seems that ilike does not work with collate,
# and Django does not use ilike anyway, but uses UPPER
# for case insensitivity.
