# Generated by Django 3.1 on 2020-11-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_break_locks',
            field=models.BooleanField(default=False, help_text='Designates whether this user can override edit locks on records, regardless of whether they own them.'),
        ),
    ]
