#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py loaddata /app/compose/local/django/site.json

python manage.py loaddata compose/local/django/superuser.json
python manage.py loaddata compose/local/django/symbols.json

python manage.py runserver_plus 0.0.0.0:8000

