version: '3.3'

volumes:
  development_postgres_data: {}
  development_postgres_data_backups: {}
  staticfiles:
  uploads:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/development/django/Dockerfile
    image: rard_development_django
    expose:
      - 5000
    container_name: django
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - type: volume
        source: uploads
        target: /uploads
      - type: volume
        source: staticfiles
        target: /static
    env_file:
      - ./.envs/.development/.django
      - ./.envs/.development/.postgres
    command: /start
    restart: always
    healthcheck:
      test:
        - CMD
        - python
        - "-c"
        - "import requests;exit(399<requests.get('http://localhost:5000',allow_redirects=False).status_code)"
      timeout: 10s
      interval: 1m
      retries: 3

  postgres:
    build:
      context: .
      dockerfile: ./compose/development/postgres/Dockerfile
    image: rard_development_postgres
    container_name: postgres
    volumes:
      - type: volume
        source: development_postgres_data
        target: /var/lib/postgresql/data
      - type: volume
        source: development_postgres_data_backups
        target: /backups
    env_file:
      - ./.envs/.development/.postgres
    restart: always
    healthcheck:
      test: "pg_isready -q -U $$POSTGRES_USER -d $$POSTGRES_DB"
      timeout: 45s
      interval: 10s
      retries: 10

  nginx:
    build:
      context: .
      dockerfile: ./compose/development/nginx/Dockerfile
    image: rard_development_nginx
    container_name: nginx
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:2345:2345"
    volumes:
      - ./compose/development/nginx/conf.d:/etc/nginx/conf.d:z
      - ./compose/development/nginx/certs:/etc/nginx/certs:z
      - ./compose/development/nginx/snippets:/etc/nginx/snippets:z
      - type: volume
        source: staticfiles
        target: /static
    depends_on:
      - django
    restart: always

