version: '3.3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  staticfiles:
  uploads:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: rard_production_django
    expose:
      - 5000
    container_name: django
    depends_on:
      - postgres
      - elasticsearch
    links:
      - postgres
      - elasticsearch
    volumes:
      - type: volume
        source: uploads
        target: /uploads
      - type: volume
        source: staticfiles
        target: /static
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: rard_production_postgres
    container_name: postgres
    volumes:
      - type: volume
        source: production_postgres_data
        target: /var/lib/postgresql/data
      - type: volume
        source: production_postgres_data_backups
        target: /backups
    env_file:
      - ./.envs/.production/.postgres

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200

  pgadmin:
    build:
      context: .
      dockerfile: ./compose/production/pgadmin/Dockerfile
    image: rard_production_pgadmin
    expose:
      - 80
    env_file:
      - ./.envs/.production/.pgadmin
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: rard_production_nginx
    container_name: nginx
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:2345:2345"
    volumes:
      - ./compose/production/nginx/conf.d:/etc/nginx/conf.d
      - ./compose/production/nginx/certs:/etc/nginx/certs
      - ./compose/production/nginx/snippets:/etc/nginx/snippets
      - type: volume
        source: staticfiles
        target: /static
    depends_on:
      - django
      - pgadmin
      - elasticsearch
