# This is a basic workflow to help you get started with Actions

name: FRRAnt-docker-tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint_and_pytest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: flake
        run: | 
          cd src
          docker-compose -f local.yml run --rm django flake8
      
      - name: local-django-pytest
        run: | 
          cd src
          docker-compose -f local.yml run --rm django pytest

  deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: build
        run: | 
          cd src
          docker-compose -f local.yml build
          docker-compose -f local.yml up -d
          docker-compose -f local.yml down
