# This is a basic workflow for deploying FRRAnt's Django web application and testing it's functionality

name: FRRAnt docker tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    #  No RHEL available, testing on ubuntu instead
    runs-on: ubuntu-latest

    steps:
      # Run tests
      - uses: actions/checkout@v2
      - name: Docker test
        run: docker-compose -f ./src/development.yml run --rm django pytest
